### ISSUE TITLE
Error with caches

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#104]
Locally it is working but in remote is like it is unable to get a dependency. I am using v2 beta 7

https://github.com/JavierSegoviaCordoba/intellij-theme-javiersc/runs/4039312589?check_suite_focus=true

**Comment by bigdaz** [comment]
@JavierSegoviaCordoba I've just released `v2.0-rc.2` which should fix this issue for you. Please give it a spin and report any problems.

**Comment by JavierSegoviaCordoba** [comment]
It is working, and just to say congratulations!

The build time has been reduced to half at minimum, even more almost always, since I am using this action instead of running commands plus the official GitHub Actions cache with the default configuration in their README.

The cache size is minimum (in a little project I have it even has less than 20MB, meanwhile with the official cache action it was taking more than 1500MB, just ridiculous the insane difference in both aspects. Again, congratulations.

**Comment by bigdaz** [comment]
Thanks for the positive feedback! One the action is stabilized my goal is to make it the official recommendation for running Gradle, and get the official docs updated.

I think you might be underestimating the amount of cache used: there's not much the action can do to reduce this since one of the dependencies is an entire Intellij distro. You can get a good overview of the cache usage here: https://github.com/JavierSegoviaCordoba/intellij-theme-javiersc/runs/4063158563?check_suite_focus=true#step:22:27
