### ISSUE TITLE
Consider adding default -XX:MaxMetaspaceSize jvmargs parameter

### ISSUE THREAD

**Issue by howelltw** [gradle/gradle-build-action#122]
There seems to be a fair amount of GitHub Workflow builds failing with out of memory type of errors, and the fact that the JVM defaults to unbounded MaxMetaspaceSize has been the culprit for many people.

The typical error appears as:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

Here is the relevant section from the Java documentation:

> In previous releases of Java Hotspot VM, the class metadata was allocated in the so-called permanent generation. Starting with JDK 8, the permanent generation was removed and the class metadata is allocated in native memory. The amount of native memory that can be used for class metadata is by default unlimited. Use the option -XX:MaxMetaspaceSize to put an upper limit on the amount of native memory used for class metadata.

Source: [https://docs.oracle.com/en/java/javase/17/gctuning/other-considerations.html](https://docs.oracle.com/en/java/javase/17/gctuning/other-considerations.html)

**Comment by bigdaz** [comment]
Is there a reason that this setting is specifically required for Gradle running on GitHub Actions, or would this improvement be useful for all Gradle invocations?

In general the responsibility for setting default JVM arguments belongs in the realm of the Gradle Build Tool, as opposed to the GitHub/Gradle integration. That way, the same benefits would apply if the build was executed on Jenkins, TeamCity or any other CI server.

**Comment by bigdaz** [comment]
I'm going to close this issue pending an answer to ☝️

**Comment by howelltw** [comment]
Sorry, I missed the notification on your previous question. The need for this setting is not specific to Gradle running on Github Actions, but might be nice to add when running on such a memory constrained platform.

People can of course set this parameter outside of the Action, it just felt like a nice opportunity to save other users the headache of having to troubleshoot this problem. (And no amount of debug logging from Gradle gave me any hint that it was MaxMetaspaceSize related.)

**Comment by 3flex** [comment]
Related to https://github.com/gradle/gradle/issues/19648? Both issues relate to Gradle builds running in memory-constrained environments, though one is about metaspace and the other about max memory allocation.

**Comment by bigdaz** [comment]
Thanks for the added information. I'm engaging with the Gradle Build Tool team to discuss the best way forward. It makes sense for Gradle (or the `gradle-build-action`) to do some sanity checks on the requested memory settings based on the environment it's running in.

**Comment by bigdaz** [comment]
As you can see in gradle/gradle#19750, Gradle is already setting a default value for `-XX:MaxMetaspaceSize`, but a bug is causing this value to be lost when any other value is provided for `org.gradle.jvmargs`.

So the best solution would be to fix this in Gradle, but we could possibly provide some sort of workaround in the action. A workaround would address this problem for versions of Gradle where this issue is not fixed.

**Comment by bigdaz** [comment]
Looking more deeply at the Gradle code, I don't see any way for the `gradle-build-action` to set a default value for `-XX:MaxMetaspaceSize` that would not be lost when a user explicitly configures `org.gradle.jvmargs`. This is because the `org.gradle.jvmargs` values are not merged, so any defaults will be completely overwritten by a user-provided value.

In the end, this issue needs to be fixed in Gradle, and in the meantime users will need to always specify `MaxMetaspaceSize` when configuring `org.gradle.jvmargs`.
