### ISSUE TITLE
Ability to only write to cache

### ISSUE THREAD

**Issue by khouari1** [gradle/gradle-build-action#141]
Is it possible to only write to the cache? I see there is a configurable property to only read from cache but it doesn't seem like you can do this for write.

I would like to have the default branch build only write to the cache so it is a full clean build each time, and feature branch builds would only read from the cache.

If this is not currently possible, would it be a feature you would be open to supporting?

Thanks

**Comment by bigdaz** [comment]
Hi. This isn't currently possible but would probably be a worthwhile feature to add.

Can I ask why you want to avoid restoring the Gradle User Home for the default branch build? Is there some particular state in Gradle User Home that would make you not trust that you are getting a "full clean build"?

**Comment by khouari1** [comment]
I would think that in the vast majority of cases (maybe even all) the build using the cache would be reliable. But it's difficult to know that for sure so being able to run a clean build, maybe nightly, would help to be sure that there are no issues with the build that perhaps the cache may otherwise hide. I'm certainly no gradle expert so could be wrong but think it might be a useful thing to do occasionally.

**Comment by bigdaz** [comment]
It's a bit confusing because there are multiple "caches" involved here. The `gradle-build-action` is _not_ doing anything to enable caching for the Gradle build itself. Each build uses a fresh checkout of the source code, and runs a "clean" build in this checkout.

The primary "cache" in the `gradle-build-action` is saving and restoring parts of the `~/.gradle` directory between build invocations. This allows Gradle to avoid re-downloading dependencies and wrapper zips every time. It's the same as if you ran a Gradle build on your machine, did a fresh `git clone` and ran the build a second time.

In general, there should _never_ be a need to start with an empty `~/.gradle` directory, because Gradle should _always_ produce the same results irrespective of the state of this directory. But it's possible to construct a build where this isn't the case, and I do understand the desire to start with a "clean slate" at times.

**Comment by khouari1** [comment]
Ah ok, understood. Thank you for explaining that, much appreciated.

**Comment by bigdaz** [comment]
I just merged a change that adds an experimental `cache-write-only` option. This feature will be included in the next release.

**Comment by khouari1** [comment]
Awesome, thanks :)
