### ISSUE TITLE
Write caches on main branch only by default

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle-build-action#143]
In https://github.com/gradle/gradle-build-action/issues/120#issuecomment-968997996 it was stated that there was consideration of changing the config default so the cache is only written from main branch, thus preventing many PR builds from exhausting available cache and evicting the main branch's cache.

Just creating this issue for tracking (or rejection). I think it makes sense to change the default.

**Comment by bigdaz** [comment]
I'm more and more convinced that this is a good idea, but I'm not sure how to model it.

Option 1: keep `cache-read-only` as is, but change the default value when it's not set.
- Can explicitly set to either 'true' or 'false'
- Default will be to use the GH API to determine the default branch, and use 'true' unless the current branch == default branch.

Option 2: Add a 'cache-write-branches' parameter (or something with a better name). Only builds on these branches (or matching a pattern) would write to the cache.
- Default this to the repository default branch name
- User could then provide something like `cache-write-branches: main, release, feature-*`

Option 2 is really just a more convenient way of specifying option 1. So I think I'd start with Option 1 and leave Option 2 open for later.

**Comment by bigdaz** [comment]
This was surprisingly easy to implement: e1f5f66e7c8a6aaf6bed47666673e91887598a6b

However, I'm a little wary since this would have a negative impact on projects that do their primary development on a non-default branch. For instance, a project that uses 'main' for their latest stable release and some other branch for active development.
I don't really have a good answer here: this change will give a mild benefit many users who will get more efficient caching, but might have a significant negative impact on a smaller set of users (who would get no caching at all).

**Comment by bigdaz** [comment]
For reference, here is the documentation where we recommend this pattern: https://github.com/gradle/gradle-build-action#only-write-to-the-cache-from-the-default-branch

**Comment by bigdaz** [comment]
I think we should add this in `v2.2.0`, with an appropriate message in the Job Summary informing users that the cache is read-only and why.
