### ISSUE TITLE
Question: isn't this supposed to cache the state of the gradle tasks?

### ISSUE THREAD

**Issue by gotson** [gradle/gradle-build-action#152]
Hi,

i'm trying to test this action in my build, and my understanding was that it would cache the state of the tasks, which would reduce the build time by having more tasks `UP TO DATE`, thus not having to rerun them.

However, it doesn't seem to be the case in my test, but maybe i missed something ?

Here is a [run](https://github.com/gotson/komga/runs/5001179152?check_suite_focus=true), for which i would have expected the `test-gradle` job to use some of the cache from the previous `Test JDK 8` job, however none of the tasks were up to date, and had to be run again.

Would you be able to clarify whether my assumptions are correct or not, and if they are, would you be able to help me understand why it didn't work as expected?

Thanks

**Comment by bigdaz** [comment]
Unfortunately, there's a lot of different things that are referred to as "cache", and it gets confusing.
[As described](https://github.com/gradle/gradle-build-action#caching) the `gradle-build-action` will save part of your Gradle User Home directory (normally `~/.gradle`) as well as some specific configuration-cache state. The action definitely _does not_ save your project's _build output_ directory, and this state is what's used when a task is `UP TO DATE`.

However, you can benefit from the [Gradle Build Cache](https://docs.gradle.org/current/userguide/build_cache.html) which provides many of the benefits of `UP TO DATE` tasks with less overhead. This works because the local build cache state is stored in the Gradle User Home directory, and so is saved/restored by the action. (It's worth reading the linked doc to get a better idea of how the build cache works.)

So by default you will see all of your tasks executing every time. But if you enable the build cache (with local build caching), you should start to see benefits of reusing task outputs from previous builds.

**Comment by gotson** [comment]
Thanks @bigdaz for the explanations. I tried to enable `--build-cache`, but the tasks are still not `UP TO DATE`. [Here](https://github.com/gotson/komga/runs/5061399666?check_suite_focus=true) is the run. Would you know what's missing to enable caching with the `gradle-build-action` ?

**Comment by bigdaz** [comment]
You won't see tasks being `UP TO DATE`, because this only happens if the build output directory already exists.
I suggest you first get the build cache working locally, and then see if you can translate that onto your GitHub actions pipeline.

When `--build-cache` is working properly, you can do something like `./gradlew clean build` and you'll see the task outputs coming `FROM CACHE`. If it's not working for you locally, then it won't work with `gradle-build-action`. 

Please read these docs to get a better understanding of the Gradle build cache: https://docs.gradle.org/current/userguide/build_cache.html.

**Comment by gotson** [comment]
It does work on my machine:

```
> ./gradlew --build-cache clean assemble
BUILD SUCCESSFUL in 7s
21 actionable tasks: 12 executed, 9 from cache
```

Doesn't work when using the action though.

**Comment by gotson** [comment]
I have enable the debug logs for the cache to provide more information.

For the [JDK 8 build](https://github.com/gotson/komga/runs/5062898748?check_suite_focus=true), after the first run, the subsequent runs benefit from the cache: `35 actionable tasks: 16 executed, 19 from cache`

However for the other tasks, the cache is not used or only for a single task:
- [JDK 11](https://github.com/gotson/komga/runs/5062898786?check_suite_focus=true) `35 actionable tasks: 34 executed, 1 from cache`
- [JDK 17](https://github.com/gotson/komga/runs/5062898821?check_suite_focus=true) `35 actionable tasks: 34 executed, 1 from cache`
- [test-gradle](https://github.com/gotson/komga/runs/5062934010?check_suite_focus=true) `16 actionable tasks: 16 executed`

I checked the cache keys and restore keys, and the restore keys should allow the use of the cache populated by the JDK 8 job, but doesn't seem to work.

Any hints on how to diagnose what the problem is?

**Comment by bigdaz** [comment]
There are many reasons that you can see cache misses for a build. For example, for many tasks the JDK version is part of the cache key, and you'd expect to see cache misses if you run on a different JDK. Again, I'd suggest that you test this locally (using multiple JDKs) to verify. If you can, I highly recommend that you use build scans to get deeper insight into what's going on. There's some good hints/information here: https://docs.gradle.org/current/userguide/build_cache_debugging.html

That said, I can see an issue with your GitHub Actions that might be a problem too:
- For [Test JDK 8](https://github.com/gotson/komga/runs/5062898786?check_suite_focus=true#step:10:11) you can see the cache entries being restored and saved 
- But with [Test JDK 11](https://github.com/gotson/komga/runs/5062898786?check_suite_focus=true#step:10:11) you can see that it's _not_ using the entry produced by `Test JDK 8`, but instead it's using an entry produced by a prior `Test JDK 11` run. (The bit in the square brackets is the hash of the matrix parameters)

This is odd because you have `cache-read-only: true` for `Test JDK 11`, but I strongly suspect that you didn't always have this setting, resulting in a pre-existing Gradle User Home cache entry for `Test JDK 11` which is being preferred over the more recent `Test JDK 8` entry. The GitHub cache keys being requested can be seen in the logs [here](https://github.com/gotson/komga/runs/5062898786?check_suite_focus=true#step:4:18).

**Comment by gotson** [comment]
> but I strongly suspect that you didn't always have this setting, resulting in a pre-existing Gradle User Home cache entry for `Test JDK 11` which is being preferred over the more recent `Test JDK 8` entry.

That's true. How can one clear those cache entries?

---

I'm mostly interested in the other `test-gradle` job which is using jdk 8 also, but doesn't use the cache at all. It never produced a cache entry either. 

> The GitHub cache keys being requested can be seen in the logs [here](https://github.com/gotson/komga/runs/5062898786?check_suite_focus=true#step:4:18).

I have seen those, but I don't see anywhere what's the actual key that's hit and restored?

**Comment by bigdaz** [comment]
> That's true. How can one clear those cache entries?

It's not possible. See [this issue](https://github.com/gradle/gradle-build-action/issues/115) related to this problem, and particularly [this comment](https://github.com/gradle/gradle-build-action/issues/115#issuecomment-1013981903) which describes a workaround.

Note that you can set the `env` variable globally for all steps in all jobs in a workflow: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env

> I'm mostly interested in the other `test-gradle` job which is using jdk 8 also, but doesn't use the cache at all. It never produced a cache entry either.
> 
> > The GitHub cache keys being requested can be seen in the logs [here](https://github.com/gotson/komga/runs/5062898786?check_suite_focus=true#step:4:18).
> 
> I have seen those, but I don't see anywhere what's the actual key that's hit and restored?

There's a summary of all cache entries requested and restored [here in the post action logs](https://github.com/gotson/komga/runs/5062934010?check_suite_focus=true#step:6:10). Using that summary, I can see that there is indeed a cache entry produced by an earlier `test-gradle` job.

Note that renaming the `test-gradle` job would be another way to reset the state and avoid using this prior cache entry, since the job name is part of the key.
