### ISSUE TITLE
Support using a custom Gradle distribution

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle-build-action#2]
With a `gradle-distribution` input that can point either to a local or a remote distribution.

I don't have the need for it yet, if you do, please add a 👍 .

**Comment by bigdaz** [comment]
The `gradle-build-action` can now be used to setup the Gradle User Home so that any arbitrary Gradle invocations will benefit from enhanced caching and build-scan integration. This should make it relatively straightforward to use a custom Gradle distribution if required (although a downloading, installing and caching a remote distribution would need to be managed by the user).
