### ISSUE TITLE
Download Gradle - WebSocketException issue

### ISSUE THREAD

**Issue by bissquit** [gradle/gradle-build-action#346]
Hello! I ran gradle-build-action on self-hosted runners but faced with `download failed` error. Runners use proxy to access internet.
Could you please advise how to debug such issues and what could be a problem?
Maybe there is an option to type particular download path?

```
Provision Gradle 6.8
  ##[debug]Resolved Keys:
  ##[debug]["gradle-6.8"]
  ##[debug]Checking zstd --version
  ##[debug]Unable to locate executable file: zstd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
  ##[debug]
  ##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/xSjIst2jWPNvK8bjL8sv6FJrgzZpiWpEIEZg/_apis/artifactcache/cache?keys=gradle-6.8&version=427f7659e1359c69405135451e6ad4837fb2a97e5fe49
  Gradle distribution 6.8 not found in cache. Will download.
  ##[debug]Downloading https://services.gradle.org/distributions/gradle-6.8-bin.zip
  ##[debug]Destination /github/home/gradle-installations/downloads/gradle-6.8-bin.zip
  ##[debug]download failed
  aborted
  Waiting 10 seconds before trying again
  ##[debug]download failed
  aborted
  Waiting 12 seconds before trying again
  ##[debug]download failed
  ::endgroup::
Error: Error: aborted
Error: aborted
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketCloseListener (node:_http_client:407:19)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at Socket.done (node:_tls_wrap:580:7)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:3[90](https://github.com/<org_name>/<repo_name>/runs/7072766419?check_suite_focus=true#step:6:92):28)
    at TCP.<anonymous> (node:net:687:12)
```

**Comment by bigdaz** [comment]
The `gradle-build-action` uses [@actions/tool-cache](https://github.com/actions/toolkit/blob/main/packages/tool-cache/src/tool-cache.ts#L38-L42) to download the Gradle distribution from `https://services.gradle.org`. There is no current way to change the download location.

If your runner uses a proxy to access the internet, I suspect that some additional auth/headers are required by the [toolCache.downloadTool](https://github.com/gradle/gradle-build-action/blob/main/src/provision.ts#L136) method call.

Some questions:
- Does your build have the Gradle wrapper configured?
- If so, does your build work if you execute using the Gradle wrapper, so that `gradle-build-action` does not need to download a Gradle distribution? (You can test by removing the `gradle-version` parameter or by using `gradle-version: wrapper`)
- If this works, how are you providing the correct proxy settings for Gradle to use?

**Comment by bissquit** [comment]
Download starts but cannot finish. It seems like action couldn't finish downloading correctly or proxy breaks tls session after download completed.
I can exec into container and I see how file is downloading but it couldn't fully complete download because of error.

I'll answer your questions later after testing. Thank you!

**Comment by bissquit** [comment]
I need a bit more time. I'll configure test env again and answer you questions.

**Comment by bissquit** [comment]
It seems now top-level proxy works fine so I can't reproduce a bug((
I think the issue may be closed. I'll reopen it if I face a bug again and can answer your questions above
