### ISSUE TITLE
Feature request: support milestones the same way as RCs are supported

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle-build-action#40]
It seems gradle is using these more: https://docs.gradle.org/6.8-milestone-3/release-notes.html

**Comment by bigdaz** [comment]
Unfortunately there's no way for us to easily get the latest milestone version, since there is no metadata available here: https://services.gradle.org/versions/. 
Because of this, I'm not sure it's worth adding this as a first class feature. If we end up with a series of 8.0 milestones we can reconsider.

**Comment by ZacSweers** [comment]
Does Gradle not control what information is in that metadata? Part of this proposal was to add that differentiation

**Comment by bigdaz** [comment]
It does control the metadata. But milestones are not (yet) part of any official release process, and there's no guarantee that we'll be using them again in the future. I'm happy to re-open this if you like, but I'm not sure it's worth the effort to implement.
