### ISSUE TITLE
Breaking change: cache-read-timeout removal

### ISSUE THREAD

**Issue by krzema12** [gradle/gradle-build-action#415]
Hi Gradle Team!

I'm the owner of https://github.com/krzema12/github-actions-kotlin-dsl/ and your action has first-class support there.

We have an automated job that helps us keep generated Kotlin wrappers in sync with actions' manifests. It just started failing with this message:

```
Request contains invalid properties:
Available: [gradle-version, cache-disabled, cache-read-only, cache-write-only, gradle-home-cache-includes, gradle-home-cache-excludes, arguments, build-root-directory, gradle-executable, generate-job-summary, gradle-home-cache-strict-match, workflow-job-context, gradle-home-cache-cleanup]
Invalid:   [cache-read-timeout]
```

which means that we tried to set a type to an input that was previously present, but it's not there any more. It happened in this commit: https://github.com/gradle/gradle-build-action/commit/8a386f6915ae17c2546e55c86fd283b608ae51da

According to semver, such changes should be accompanied with bumping the major version. Otherwise, the users need to adjust their workflows. For us (Kotlin DSL maintainers) it's not a big deal, but just wanted to give you feedback to perhaps avoid such cases in the future, or properly communicate them using semver rules. It can save headache for your customers 😄 

Cheers!

**Comment by bigdaz** [comment]
Thanks for pointing that out. I am aware of the semver requirements, but believe there are mitigating circumstances in this case:
- The property was added to the [EXPERIMENTAL & INTERNAL ACTION INPUTS](https://github.com/gradle/gradle-build-action/blob/v2.2.3/action.yml#L61-L72) section of `action.yml`. These are called out as being subject to change without notice.
- The `cache-read-timeout` property was never documented or announced.
- The property was added in `2.2.3` and removed in `2.3.0` less than 2 weeks later.

In retrospect, I guess I should have simply deprecated the property for removal in the next major. But I didn't do that because I believed it wouldn't impact any users. I guess I was wrong :). My apologies.

**Comment by krzema12** [comment]
Ah, it was an internal one... Got it, thanks! Too bad GitHub doesn't have a way to communicate it via its action.yml with some attribute.
