### ISSUE TITLE
v2.3.0 does not appear to actually cache wrapper binaries separately

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle-build-action#438]
Repro: https://github.com/slackhq/circuit/pull/125

Gradle binaries appear to get redownloaded every time https://github.com/slackhq/circuit/actions/runs/3095125981/jobs/5009299881#step:5:30

**Comment by bigdaz** [comment]
By default, the action will set `cache-read-only: true` for all jobs, except those run on the default branch. https://github.com/gradle/gradle-build-action#using-the-caches-read-only
This was done because cache entries are not visible between sibling branches, and is an attempt to avoid having useful shared entries evicted by "private" entries written for a particular branch. [Read here](https://github.com/gradle/gradle-build-action#select-branches-that-should-write-to-the-cache) for a detailed explanation.

To test this functionality, I suggest you test with `cache-read-only: false` in your PR. You can use the[ job summary](https://github.com/slackhq/circuit/actions/runs/3095125981#summary-8464572298) to understand exactly which entries are being saved and restored.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/179734/191539653-b6945773-313b-4a5a-b1da-20a36c442d37.png">

**Comment by ZacSweers** [comment]
Got it! I misunderstood the default behavior there, will take a look
