### ISSUE TITLE
Is there a way to use this action with a `gradle-wrapper.properties` file?

### ISSUE THREAD

**Issue by shichen85** [gradle/gradle-build-action#505]
I am building my project through a 3rd party app that uses a `gradle-wrapper.properties` file. I want to edit the `gradle-wrapper.properties` file to let it use the gradle provisioned by `gradle-build-action` so the 3rd party app does not download gradle again. I would appreciate some pointers on how to achieve that. The original `gradle-wrapper.properties` file looks like this:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by bigdaz** [comment]
The relevant values in`gradle-wrapper.properties` are `distributionBase` and `distributionPath`. Since those appear to be unmodified from the default values, the `gradle-build-action` should save and restore wrapper distributions between invocations.
Is this not what you are seeing? If not, can you share more details of the behaviour you're seeing?

**Comment by bigdaz** [comment]
When you specify a `gradle-version` parameter, the _action_ will download, extract and cache the relevant Gradle distro. This installation is then added to the `PATH` so that any subsequent `gradle` commands will use it.

This mechanism is completely separate from distributions downloaded by the Gradle Wrapper. If all of your Gradle invocations use `gradlew` (not `gradle`), then you can safely omit the `gradle-version` parameter, and the action won't download Gradle 7.4 unnecessarily.
