### ISSUE TITLE
Keep Daemon alive

### ISSUE THREAD

**Issue by JD10NN3** [gradle/gradle-build-action#573]
I'm using a Self Host Long-live runner and I would like the daemon to be kept alive. 
Is there a way to avoid stoping all daemon at the post step?

Thanks for your help

**Comment by bigdaz** [comment]
Yes, the daemon is only stopped in order to save the Gradle User Home state to the GitHub Actions cache. See here for more details: https://github.com/gradle/gradle-build-action/blob/main/README.md#stopping-the-gradle-daemon

There are a few cases where the daemon will not be stopped:
- `cache-read-only` is set to `true
- The Gradle User Home already exists when the build starts, meaning the it will not be restored from the cache.
