### ISSUE TITLE
how to setup isolated caches for multiple projects in the same repo

### ISSUE THREAD

**Issue by yigit** [gradle/gradle-build-action#75]
This is more of a question than a feature request :), asking for some advice.

In AndroidX, we build multiple projects in paralel. As such, their dependencies are different, hence we tried to separate them by giving each of them a different key (to avoid them overriding each-other's cache)
This created another downside where it simply does not upload the cache due to the hit. (see warm up gradle step here: https://github.com/androidx/androidx/runs/3550347353?check_suite_focus=true)

Is it possible to pass multiple list of keys where we can control the fallback mechanism when the first hit does not match.
e.g. we have N projects, for each of them, we want to specify two keys:

```
projectName-withGradleFilesHash
projectName
```
https://github.com/androidx/androidx/pull/242/files

We actually don't even want it to fallback to the default `dependencies` if these two caches fail, as it will result in building on top of another project's dependencies (hence use more space in the 5GB limit).

As far as I can read this code, it currently uses 2 keys:
1) a key with given parameters
2) fallback to dependencies
https://github.com/gradle/gradle-build-action/blob/b3afdc78a7849557ab26e243ccf07548086da025/src/cache-dependencies.ts#L39

It would be great if there was a way to pass the list of keys (and we can enable exact match for these keys to avoid the default dependency)

We are also open to suggestions if there is a better way to do this.

Thanks!

**Comment by bigdaz** [comment]
Thanks for the report @yigit, this is timely.

I'm currently working on a `gradle-build-action@v2`. In it's present state, the cache key generation/matching is similar to what you're asking for (although there is not yet any user-configurable options). You can see the logic here: https://github.com/gradle/gradle-build-action/blob/releases/v2/src/cache-utils.ts#L29-L51.

At first I was trying to hash the project-name and the arguments list, but this was problematic since the cache is restored/saved only at the start/end of the entire GitHub Workflow _job_, which can involve multiple Gradle invocations with multiple projects and different tasks requested. So instead, the cache key is made up of:
- The `job` id/name
- The hashed `matrix` for the job
- The current git SHA for the entire repo

This has the benefit of tying the cache output with the actual job invocation, and provides the maximum caching benefit. There are downsides that I'm currently working to mitigate:
- Tying the cache key to the repository commit ID means that even if the cached directories are unchanged after build invocation, a new cache entry will be saved with a new cache key.
- Having different cache entries for different job invocations (eg JDK 8 vs JDK 11) can result in a lot of duplication of values within the cache.

My goal is to:

1. Provide the maximum benefit for small/medium projects with absolutely no additional configuration required. 
2. Ensure that larger projects can tweak things to maximise their cache usage without suffering from endless cache eviction.

I'll add `androidx` to the set of projects that I've testing with, so I can monitor how I'm going on the second point.

**Comment by bigdaz** [comment]
PS I don't plan on addressing this in v1 of the build action, but would be open to a PR if you are particularly keen.

**Comment by yigit** [comment]
Oh interesting.
the multiple gradle invocations was the exact reason why we've added that warm up task. Each sub-project runs with the same arguments first and then runs with its own build actions (so the cache key for the actual build never worked as all parallel tasks used the key from the first invocation that was the same for all)

We are also not interested in things like `os`, `jvm` as the main goal here is to cache maven dependencies. (though could matter for other projects)

In terms of new cache entries, as long as there is a good fallback mechanism, i'm not sure how bad it is. Maybe the biggest downside is that every job run will upload the cache regardless, hence doing more upload work when not needed. (though it seems fast enough). I'm also hoping that Github implemented an LRU for that cache so it should act well in practice. But if someone invokes gradle multiple times, they probably want the gradle cache to be shared, otherwise, you'll just end up uploading the same content multiple times as it happens after job completes. Also, LRU may not perform best as people might have different post submit workflows which run way less, hence their cache may not stay recent in an LRU cache.

Btw, I'm not sure what `matrix` for the job contains. If it only contains the matrix parameters passed into that job (vs all matrix options), that might be the perfect solution for our case.

If that assumption is correct, this would even work out of the box for AndroidX(almost). Regardless though, i think for advanced use cases, letting caller take full control of caching keys seems like a feasible option? I'll see if we can prototype it over v1 and send a PR if it seems to make sense.

Thank you!

**Comment by bigdaz** [comment]
A job configured like this:
```
strategy:
  matrix:
    java: [ 11, 12 ]
    os: [ ubuntu-latest, macos-latest ]
```
will have a `matrix` context object like this for the first run:
```
{
  "java": 11,
  "os": "ubuntu-latest"
}
```.

So combined with the job name / id this provides a good way to uniquely identify a particular job execution over time.

**Comment by bigdaz** [comment]
Note that `v2` of the action will do caching a bit differently:
- The Gradle User Home (or portions thereof) will be cached with a key that is unique for the actual invocation. This key includes the git SHA so we make no assumptions about what particular files or build parameters will impact the Gradle User Home.
- Within the Gradle User Home, many common zips and jars will be deduplicated and cached with a fixed id. This works by:
  1. Before caching the Gradle User Home, each of these jars is replaced by a marker file and cached separately
  2. When restoring the Gradle User Home, the jar/zip is restored for any marker file detected

In testing this has a huge impact on reducing the overall size of the cache entry that is specific to a job invocation. I will be interested to see how this works for the AndroidX project.

**Comment by yigit** [comment]
yea reducing cache size might actually help a lot for us.

I'm happy to collaborate here to make AndroidX a test bed. Our main development happens in AOSP so we have more flexibility in breaking Github (though not desired as we get a steady stream of PRs there).

Or we can even have a running PR that changes it to v2 and work on it (or on a branch).

**Comment by yigit** [comment]
so i made a quick and dirty prototype here on what i was thinking:

https://github.com/yigit/gradle-build-action/commit/eadf30afbc7bc3e33e53c1bfcf9f83f089d801bb

beware,I've not tried this nor I know TS so this might be stupid :) I basically copied how github's cache action reads `restore-keys` and copied.

Lmk what you think, if it sounds reasonable, i can test this and try to send a PR. Meanwhile, it seems like there is no v1 branch to merge back into? (I've created this from 1.5.1 tag)

Btw. I'm not sure why the action is failing, i've run `npm run-script build` and uploaded everything.
https://github.com/yigit/gradle-build-action/runs/3628537290

**Comment by bigdaz** [comment]
Closing this issue, as we've moved on a long way from the implementation in v1.
