### ISSUE TITLE
Action fails on Windows

### ISSUE THREAD

**Issue by melix** [gradle/gradle-build-action#94]
Hi team!

I was trying to use this action in a build matrix which has a Windows agent. The builds are failing with:

> EBUSY: resource busy or locked, unlink 'C:\Users\runneradmin\.gradle\caches\7.2\generated-gradle-jars\gradle-api-7.2.jar'

You can find an example at https://github.com/melix/mrjar-gradle-plugin/actions/runs/1341956391

It seems to be a reproducible issue, re-enabling Windows testing fails again. Probably a file locking issue.

**Comment by bigdaz** [comment]
Thanks for trying it out, @melix.

I suspect that you're hitting #89 which was [fixed in the `v2.0-beta.4` release of the `gradle-build-action`](https://github.com/gradle/gradle-build-action/releases).

From the [workflow logs](https://github.com/melix/mrjar-gradle-plugin/runs/3895069801?check_suite_focus=true#step:1:32) I can see that this build was run with `gradle-build-action@v2.0-beta.3`. Even though I fixed the issue a couple of weeks ago, I didn't remember to update the `v2` tag until a few days back, which would explain why you were using an outdated version.

Can you please check if you've experienced this issue this week, or with any build using a later version of the `gradle-build-action`?
